{
 "title": "FastAPI Application Metrics",
 "tags": [
  "fastapi",
  "lab7",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "FastAPI Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, path, status_code) (rate(fastapi_http_requests_total[1m]))",
     "legendFormat": "{{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "FastAPI p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(fastapi_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95 {{path}}"
    }
   ]
  },
  {
   "title": "Custom: Users In DB",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_users_total" }
   ]
  },
  {
   "title": "Custom: Total Purchase Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_orders_total_purchase_price"
    }
   ]
  },
  {
   "title": "Custom: User Changes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(app_users_created_total[10m])",
     "legendFormat": "created"
    },
    {
     "expr": "increase(app_users_deleted_total[10m])",
     "legendFormat": "deleted"
    }
   ]
  }
 ]
}